source ~/.config/mde/main 2>/dev/null
#ps aux | grep -v grep | grep -q ssh-agent || eval $(ssh-agent -s)
eval $(ssh-agent -s) # how to reuse already running agent?
microde-ssh-keys.sh
microde-ssh-tunnels.sh &

if [[ $(tty) == /dev/tty1 ]]
then
	echo "startx? (Y/n)"
	read resp
	[ -z "$resp" -o "$resp" == 'y' -o "$resp" == 'Y' ] && startx
fi
